### ISSUE TITLE
error: no matching package named `salsa20-core` found

### ISSUE THREAD

**Issue by DAOCUONG** [web3infra-foundation/libp2p-rs#27]
Add libp2p-rs to cargo.toml 
Run cargo build 

Got error cause salsa20-core is abandance

**Comment by restoreall** [comment]
Hi @DAOCUONG ,

Salsa20-core is a dependency for salsa20 and it was yanked on Febuary 3rd. So you can clone our repo to local, manually change salsa20 to version 0.6.0 in core/src/Cargo.toml and use this dependency in your Cargo.toml. We will fix it in next release.

Thanks for your attention to libp2p-rs.

**Comment by macrocan** [comment]
> Hi @DAOCUONG ,
> 
> Salsa20-core is a dependency for salsa20 and it was yanked on Febuary 3rd. So you can clone our repo to local, manually change salsa20 to version 0.6.0 in core/src/Cargo.toml and use this dependency in your Cargo.toml. We will fix it in next release.
> 
> Thanks for your attention to libp2p-rs.

Also, You can refer to latest commit (ebd1b57b) in @kingwel-xie[ fork](https://github.com/kingwel-xie/libp2p-rs)

**Comment by DAOCUONG** [comment]
Thanks for helping
