### ISSUE TITLE
Compilation failed due to dependency issues

### ISSUE THREAD

**Issue by andeya** [web3infra-foundation/libp2p-rs#37]
**Describe the bug**
```
error: failed to select a version for the requirement `aesni = "^0.7"`
candidate versions found which didn't match: 0.99.99, 0.10.0, 0.9.0, ...
location searched: crates.io index
required by package `aes-ctr v0.4.0`
    ... which satisfies dependency `aes-ctr = "^0.4.0"` of package `libp2prs-secio v0.3.0 (/Users/henrylee2cn/rust/libp2p-rs/protocols/secio)`
    ... which satisfies path dependency `libp2prs-secio` (locked to 0.3.0) of package `libp2prs-yamux v0.3.0 (/Users/henrylee2cn/rust/libp2p-rs/protocols/yamux)`
```

**To Reproduce**
1. cargo +nightly check

**Additional context**
- x86_64-apple-darwin
- rustc 1.60.0-nightly (6abb6385b 2022-01-26)

**Comment by restoreall** [comment]
Hi @henrylee2cn ,

This bug has been fixed at [this commit](https://github.com/kingwel-xie/libp2p-rs/tree/0c4615382f60023bc24c784f77407e143fb38ebc). You can use this [fork](https://github.com/kingwel-xie/libp2p-rs) to compile again. We are still doing other works, so the update may be delayed.

If you have another issues, please tell us. 

Thanks for your attention to libp2p-rs.
